import { formatDate, formatCurrency } from './formatters.js';

export const exportCompaniesCSV = (companies) => {
  if (!companies || companies.length === 0) { alert('No companies to export'); return; }
  const headers = ['Company Name', 'Total Given (₹)', 'Total Received (₹)', 'Pending Balance (₹)', 'Status'];
  const rows = companies.map(c => [
    c.companyName,
    c.totalGiven.toFixed(2),
    c.totalReceived.toFixed(2),
    c.balance.toFixed(2),
    c.status
  ]);
  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  downloadFile(csv, 'companies.csv', 'text/csv');
};

export const exportTransactionsCSV = (transactions, companyName) => {
  if (!transactions || transactions.length === 0) { alert('No transactions to export'); return; }
  const headers = ['Date', 'Type', 'Amount (₹)', 'Reference', 'Notes'];
  const rows = transactions.map(t => [
    formatDate(t.date), t.type, t.amount.toFixed(2), t.reference || '-', t.notes || '-'
  ]);
  const csv = [
    `Transactions - ${companyName}`,
    `Exported on: ${new Date().toISOString()}`, '',
    headers.join(','), ...rows.map(r => r.join(','))
  ].join('\n');
  downloadFile(csv, `transactions-${companyName}.csv`, 'text/csv');
};

export const exportCompanyReport = (company, transactions) => {
  const reportDate = new Date().toISOString().split('T')[0];
  const content = [
    'COMPANY RECEIVABLE REPORT',
    `Report Date: ${reportDate}`,
    '',
    'COMPANY INFORMATION',
    `Company Name: ${company.companyName}`,
    `Status: ${company.status}`,
    `Notes: ${company.notes || 'N/A'}`,
    '',
    'FINANCIAL SUMMARY',
    `Total Given:    ${formatCurrency(company.totalGiven)}`,
    `Total Received: ${formatCurrency(company.totalReceived)}`,
    `Pending Balance:${formatCurrency(company.balance)}`,
    `% Received:     ${company.totalGiven > 0 ? ((company.totalReceived / company.totalGiven) * 100).toFixed(2) : 0}%`,
    '',
    'TRANSACTION HISTORY',
    transactions.length > 0
      ? transactions.map(t => `${formatDate(t.date)} | ${t.type} | ${formatCurrency(t.amount)} | ${t.reference || '-'} | ${t.notes || '-'}`).join('\n')
      : 'No transactions',
    '',
    '---',
    'Generated by Global Trader Receivable Tracker'
  ].join('\n');
  downloadFile(content, `report-${company.companyName}-${reportDate}.txt`, 'text/plain');
};

const downloadFile = (content, filename, mimeType) => {
  const blob = new Blob([content], { type: mimeType });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};

export default { exportCompaniesCSV, exportTransactionsCSV, exportCompanyReport };